AllCops:
  Exclude:
    - config/**/*
    - db/**/*
    - vendor/**/*
    - test/**/*

Metrics/LineLength:    
  Max: 110

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/RescueException:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/PredicateName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
