default: &default
  adapter: postgresql 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: stc_dev 
test:
  <<: *default
  database: stc_test 
production:
  <<: *default
  database: stc
